name: ${pluginName}
version: ${version}
authors: [gmlaxfanatic, Protonull]
main: com.untamedears.itemexchange.ItemExchangePlugin
description: ${description}
api-version: ${api_version}
depend: [CivModCore]
softdepend: [NameLayer, Citadel, JukeAlert]
permissions:
  itemexchange.reload:
    default: op
